2025-01-20 18:09:17,555 ERROR: Error synthesizing speech: run loop already started [in /Users/atharvdwivedi/BTech_Project_Chatbot/app.py:462]
Traceback (most recent call last):
  File "/Users/atharvdwivedi/BTech_Project_Chatbot/app.py", line 449, in synthesize_speech
    tts_engine.runAndWait()
  File "/Users/atharvdwivedi/BTech_Project_Chatbot/venv/lib/python3.10/site-packages/pyttsx3/engine.py", line 180, in runAndWait
    raise RuntimeError('run loop already started')
RuntimeError: run loop already started
2025-01-20 18:09:21,385 ERROR: Error synthesizing speech: run loop already started [in /Users/atharvdwivedi/BTech_Project_Chatbot/app.py:462]
Traceback (most recent call last):
  File "/Users/atharvdwivedi/BTech_Project_Chatbot/app.py", line 449, in synthesize_speech
    tts_engine.runAndWait()
  File "/Users/atharvdwivedi/BTech_Project_Chatbot/venv/lib/python3.10/site-packages/pyttsx3/engine.py", line 180, in runAndWait
    raise RuntimeError('run loop already started')
RuntimeError: run loop already started
2025-01-20 18:09:24,184 ERROR: Error synthesizing speech: run loop already started [in /Users/atharvdwivedi/BTech_Project_Chatbot/app.py:462]
Traceback (most recent call last):
  File "/Users/atharvdwivedi/BTech_Project_Chatbot/app.py", line 449, in synthesize_speech
    tts_engine.runAndWait()
  File "/Users/atharvdwivedi/BTech_Project_Chatbot/venv/lib/python3.10/site-packages/pyttsx3/engine.py", line 180, in runAndWait
    raise RuntimeError('run loop already started')
RuntimeError: run loop already started
2025-01-20 18:09:33,207 ERROR: Error synthesizing speech: run loop already started [in /Users/atharvdwivedi/BTech_Project_Chatbot/app.py:462]
Traceback (most recent call last):
  File "/Users/atharvdwivedi/BTech_Project_Chatbot/app.py", line 449, in synthesize_speech
    tts_engine.runAndWait()
  File "/Users/atharvdwivedi/BTech_Project_Chatbot/venv/lib/python3.10/site-packages/pyttsx3/engine.py", line 180, in runAndWait
    raise RuntimeError('run loop already started')
RuntimeError: run loop already started
2025-01-20 18:09:45,289 ERROR: Error synthesizing speech: run loop already started [in /Users/atharvdwivedi/BTech_Project_Chatbot/app.py:462]
Traceback (most recent call last):
  File "/Users/atharvdwivedi/BTech_Project_Chatbot/app.py", line 449, in synthesize_speech
    tts_engine.runAndWait()
  File "/Users/atharvdwivedi/BTech_Project_Chatbot/venv/lib/python3.10/site-packages/pyttsx3/engine.py", line 180, in runAndWait
    raise RuntimeError('run loop already started')
RuntimeError: run loop already started
2025-01-20 18:10:08,459 ERROR: Error synthesizing speech: run loop already started [in /Users/atharvdwivedi/BTech_Project_Chatbot/app.py:462]
Traceback (most recent call last):
  File "/Users/atharvdwivedi/BTech_Project_Chatbot/app.py", line 449, in synthesize_speech
    tts_engine.runAndWait()
  File "/Users/atharvdwivedi/BTech_Project_Chatbot/venv/lib/python3.10/site-packages/pyttsx3/engine.py", line 180, in runAndWait
    raise RuntimeError('run loop already started')
RuntimeError: run loop already started
2025-01-20 18:10:20,284 ERROR: Error synthesizing speech: run loop already started [in /Users/atharvdwivedi/BTech_Project_Chatbot/app.py:462]
Traceback (most recent call last):
  File "/Users/atharvdwivedi/BTech_Project_Chatbot/app.py", line 449, in synthesize_speech
    tts_engine.runAndWait()
  File "/Users/atharvdwivedi/BTech_Project_Chatbot/venv/lib/python3.10/site-packages/pyttsx3/engine.py", line 180, in runAndWait
    raise RuntimeError('run loop already started')
RuntimeError: run loop already started
2025-01-20 18:10:34,268 ERROR: Error synthesizing speech: run loop already started [in /Users/atharvdwivedi/BTech_Project_Chatbot/app.py:462]
Traceback (most recent call last):
  File "/Users/atharvdwivedi/BTech_Project_Chatbot/app.py", line 449, in synthesize_speech
    tts_engine.runAndWait()
  File "/Users/atharvdwivedi/BTech_Project_Chatbot/venv/lib/python3.10/site-packages/pyttsx3/engine.py", line 180, in runAndWait
    raise RuntimeError('run loop already started')
RuntimeError: run loop already started
2025-01-20 18:49:54,797 INFO: Mental Health Assistant startup [in /Users/atharvdwivedi/BTech_Project_Chatbot/app.py:515]
2025-01-20 18:50:00,367 INFO: Mental Health Assistant startup [in /Users/atharvdwivedi/BTech_Project_Chatbot/app.py:515]
2025-01-20 18:50:23,664 ERROR: Error synthesizing speech: run loop already started [in /Users/atharvdwivedi/BTech_Project_Chatbot/app.py:466]
Traceback (most recent call last):
  File "/Users/atharvdwivedi/BTech_Project_Chatbot/app.py", line 452, in synthesize_speech
    tts_engine.runAndWait()
  File "/Users/atharvdwivedi/BTech_Project_Chatbot/venv/lib/python3.10/site-packages/pyttsx3/engine.py", line 180, in runAndWait
    raise RuntimeError('run loop already started')
RuntimeError: run loop already started
2025-01-20 18:50:48,864 ERROR: Error synthesizing speech: run loop already started [in /Users/atharvdwivedi/BTech_Project_Chatbot/app.py:466]
Traceback (most recent call last):
  File "/Users/atharvdwivedi/BTech_Project_Chatbot/app.py", line 452, in synthesize_speech
    tts_engine.runAndWait()
  File "/Users/atharvdwivedi/BTech_Project_Chatbot/venv/lib/python3.10/site-packages/pyttsx3/engine.py", line 180, in runAndWait
    raise RuntimeError('run loop already started')
RuntimeError: run loop already started
2025-01-20 18:51:07,326 ERROR: Error synthesizing speech: run loop already started [in /Users/atharvdwivedi/BTech_Project_Chatbot/app.py:466]
Traceback (most recent call last):
  File "/Users/atharvdwivedi/BTech_Project_Chatbot/app.py", line 452, in synthesize_speech
    tts_engine.runAndWait()
  File "/Users/atharvdwivedi/BTech_Project_Chatbot/venv/lib/python3.10/site-packages/pyttsx3/engine.py", line 180, in runAndWait
    raise RuntimeError('run loop already started')
RuntimeError: run loop already started
2025-01-20 18:51:20,661 ERROR: Error synthesizing speech: run loop already started [in /Users/atharvdwivedi/BTech_Project_Chatbot/app.py:466]
Traceback (most recent call last):
  File "/Users/atharvdwivedi/BTech_Project_Chatbot/app.py", line 452, in synthesize_speech
    tts_engine.runAndWait()
  File "/Users/atharvdwivedi/BTech_Project_Chatbot/venv/lib/python3.10/site-packages/pyttsx3/engine.py", line 180, in runAndWait
    raise RuntimeError('run loop already started')
RuntimeError: run loop already started
2025-01-20 18:51:42,939 ERROR: Error synthesizing speech: run loop already started [in /Users/atharvdwivedi/BTech_Project_Chatbot/app.py:466]
Traceback (most recent call last):
  File "/Users/atharvdwivedi/BTech_Project_Chatbot/app.py", line 452, in synthesize_speech
    tts_engine.runAndWait()
  File "/Users/atharvdwivedi/BTech_Project_Chatbot/venv/lib/python3.10/site-packages/pyttsx3/engine.py", line 180, in runAndWait
    raise RuntimeError('run loop already started')
RuntimeError: run loop already started
2025-01-20 18:53:45,110 INFO: Mental Health Assistant startup [in /Users/atharvdwivedi/BTech_Project_Chatbot/app.py:519]
2025-01-20 18:53:50,670 INFO: Mental Health Assistant startup [in /Users/atharvdwivedi/BTech_Project_Chatbot/app.py:519]
2025-01-20 18:54:11,210 ERROR: Error synthesizing speech: run loop already started [in /Users/atharvdwivedi/BTech_Project_Chatbot/app.py:465]
Traceback (most recent call last):
  File "/Users/atharvdwivedi/BTech_Project_Chatbot/app.py", line 454, in synthesize_speech
    tts_engine.runAndWait()
  File "/Users/atharvdwivedi/BTech_Project_Chatbot/venv/lib/python3.10/site-packages/pyttsx3/engine.py", line 180, in runAndWait
    raise RuntimeError('run loop already started')
RuntimeError: run loop already started
2025-01-20 18:54:15,450 ERROR: Error synthesizing speech: run loop already started [in /Users/atharvdwivedi/BTech_Project_Chatbot/app.py:465]
Traceback (most recent call last):
  File "/Users/atharvdwivedi/BTech_Project_Chatbot/app.py", line 454, in synthesize_speech
    tts_engine.runAndWait()
  File "/Users/atharvdwivedi/BTech_Project_Chatbot/venv/lib/python3.10/site-packages/pyttsx3/engine.py", line 180, in runAndWait
    raise RuntimeError('run loop already started')
RuntimeError: run loop already started
2025-01-20 18:58:35,836 INFO: Mental Health Assistant startup [in /Users/atharvdwivedi/BTech_Project_Chatbot/app.py:518]
2025-01-20 18:58:41,378 INFO: Mental Health Assistant startup [in /Users/atharvdwivedi/BTech_Project_Chatbot/app.py:518]
2025-01-20 18:59:04,781 ERROR: Error synthesizing speech: run loop already started [in /Users/atharvdwivedi/BTech_Project_Chatbot/app.py:465]
Traceback (most recent call last):
  File "/Users/atharvdwivedi/BTech_Project_Chatbot/app.py", line 455, in synthesize_speech
    tts_engine.runAndWait()
  File "/Users/atharvdwivedi/BTech_Project_Chatbot/venv/lib/python3.10/site-packages/pyttsx3/engine.py", line 180, in runAndWait
    raise RuntimeError('run loop already started')
RuntimeError: run loop already started
2025-01-20 18:59:09,367 ERROR: Error synthesizing speech: run loop already started [in /Users/atharvdwivedi/BTech_Project_Chatbot/app.py:465]
Traceback (most recent call last):
  File "/Users/atharvdwivedi/BTech_Project_Chatbot/app.py", line 455, in synthesize_speech
    tts_engine.runAndWait()
  File "/Users/atharvdwivedi/BTech_Project_Chatbot/venv/lib/python3.10/site-packages/pyttsx3/engine.py", line 180, in runAndWait
    raise RuntimeError('run loop already started')
RuntimeError: run loop already started
2025-01-20 19:02:47,580 INFO: Mental Health Assistant startup [in /Users/atharvdwivedi/BTech_Project_Chatbot/app.py:517]
2025-01-20 19:02:53,105 INFO: Mental Health Assistant startup [in /Users/atharvdwivedi/BTech_Project_Chatbot/app.py:517]
2025-01-20 20:41:58,460 INFO: Mental Health Assistant startup [in /Users/atharvdwivedi/BTech_Project_Chatbot/app.py:517]
2025-01-20 20:42:04,191 INFO: Mental Health Assistant startup [in /Users/atharvdwivedi/BTech_Project_Chatbot/app.py:517]
2025-01-20 20:45:20,717 INFO: Mental Health Assistant startup [in /Users/atharvdwivedi/BTech_Project_Chatbot/app.py:517]
2025-01-20 20:45:26,227 INFO: Mental Health Assistant startup [in /Users/atharvdwivedi/BTech_Project_Chatbot/app.py:517]
